#server
server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    max-threads: 1000

#spring
spring:
  datasource:
    url: jdbc:mysql:///jtsys?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html

#mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations: /mappers/sys/*.xml

#log\uFF08\u65E5\u5FD7\uFF09
logging:
  level:
    com.cy: debug

